export const COMPANY_NAMES: Record<string, string> = {
  'SPX': 'S&P 500',
  'NDX': 'Nasdaq-100',
  'VIX': 'VIX',
  'DJI': 'Dow',
  'NVDA': 'NVIDIA',
  'MSFT': 'Microsoft',
  'GOOGL': 'Alphabet',
  'AAPL': 'Apple',
  'META': 'Meta',
  'AMZN': 'Amazon',
  'TSLA': 'Tesla',
  'PLTR': 'Palantir',
  'AVGO': 'Broadcom',
  'AMD': 'AMD',
  'SMCI': 'Super Micro',
  'JPM': 'JPMorgan',
  'BAC': 'BofA',
  'V': 'Visa',
  'MA': 'Mastercard',
  'LLY': 'Lilly',
  'UNH': 'UnitedHealth',
  'JNJ': 'J&J',
  'LMT': 'Lockheed',
  'RTX': 'Raytheon',
  'BA': 'Boeing',
  'SOFI': 'SoFi',
  'AFRM': 'Affirm',
  'SQ': 'Block',
  'COIN': 'Coinbase',
  'HOOD': 'Robinhood',
  'SNOW': 'Snowflake',
  'DDOG': 'Datadog',
  'NET': 'Cloudflare',
  'CRWD': 'CrowdStrike',
  'RIVN': 'Rivian',
  'LCID': 'Lucid',
  'ALB': 'Albemarle',
  'LAC': 'Lithium Americas',
  'INTC': 'Intel',
  'QCOM': 'Qualcomm',
  'MRVL': 'Marvell',
  'ASML': 'ASML',
  'SHOP': 'Shopify',
  'ETSY': 'Etsy',
  'W': 'Wayfair',
  'CHWY': 'Chewy',
  'ENPH': 'Enphase',
  'FSLR': 'First Solar',
  'PLUG': 'Plug Power',
  'SOUN': 'SoundHound',
  'BBAI': 'BigBear',
  'AI': 'C3.ai',
  'ARBE': 'Arbe',
  'ACHR': 'Archer',
  'RDW': 'Redwire',
  'ASTS': 'AST SpaceMobile',
  'BE': 'Bloom Energy',
  'FCEL': 'FuelCell',
  'MARA': 'Marathon',
  'RIOT': 'Riot',
  'MSTR': 'MicroStrategy',
  'CRSP': 'CRISPR',
  'BEAM': 'Beam',
  'NTLA': 'Intellia',
  'CORZ': 'Core Scientific',
  'RACE': 'Ferrari',
  'RR': 'Rolls-Royce',
  'CRWV': 'CoreWeave',
  'SERV': 'Serve Robotics',
  'ORCL': 'Oracle',
  'RGTI': 'Rigetti',
  'QBTS': 'D-Wave',
  'QS': 'QuantumScape',
  'AA': 'Alcoa',
  'TXN': 'Texas Instruments',
  'LRCX': 'Lam Research',
  'APH': 'Amphenol',
  'GEV': 'GE Vernova',
  'IBM': 'IBM',
  'VRT': 'Vertiv',
  'B': 'Barnes Group',
  'SLV': 'iShares Silver Trust',
  'RUN': 'Sunrun',
  'MRK': 'Merck',
  'PFE': 'Pfizer',
  'UUUU': 'Energy Fuels',
  'USAR': 'American Strategic Investment',
  'CCJ': 'Cameco',
  'CIEN': 'Ciena',
  'RBLX': 'Roblox',
  'AMKR': 'Amkor Technology',
  'NFLX': 'Netflix',
  'SE': 'Sea Limited'
};

export const UNIVERSE = [
  'SPX', 'NDX', 'VIX', 'DJI', 'NVDA', 'MSFT', 'GOOGL', 'AAPL', 'META', 'AMZN',
  'TSLA', 'PLTR', 'AVGO', 'AMD', 'SMCI', 'JPM', 'BAC', 'V', 'MA', 'LLY',
  'UNH', 'JNJ', 'LMT', 'RTX', 'BA', 'SOFI', 'AFRM', 'SQ', 'COIN', 'HOOD',
  'SNOW', 'DDOG', 'NET', 'CRWD', 'RIVN', 'LCID', 'ALB', 'LAC', 'INTC', 'QCOM',
  'MRVL', 'ASML', 'SHOP', 'ETSY', 'W', 'CHWY', 'ENPH', 'FSLR', 'PLUG', 'SOUN',
  'BBAI', 'AI', 'ARBE', 'ACHR', 'RDW', 'ASTS', 'BE', 'FCEL', 'MARA', 'RIOT',
  'MSTR', 'CRSP', 'BEAM', 'NTLA', 'CORZ', 'RACE', 'RR', 'CRWV', 'SERV', 'ORCL',
  'RGTI', 'QBTS', 'QS', 'AA', 'TXN', 'LRCX', 'APH', 'GEV', 'IBM', 'VRT', 'B',
  'SLV', 'RUN', 'MRK', 'PFE', 'UUUU', 'SOUN', 'USAR', 'CCJ', 'CIEN', 'RBLX', 
  'AMKR', 'NFLX', 'SE'
];

export const TEST_TICKERS = ['RACE', 'AMD', 'NVDA', 'GOOGL', 'BA'];

export const DEFAULT_CONFIG = {
  minConviction: 60,
  maxSignals: 5,
  cacheDuration: 14400, // 4 hours in seconds
};

export const CACHE_KEY_PREFIX = 'hj_scanner_';

export const STRATEGY_LABELS = {
  Z_SCORE_REVERSION: '📊 Z-Score Reversion',
  MOMENTUM_REGIME: '🚀 Momentum+Regime',
  RELATIVE_STRENGTH: '💪 Relative Strength',
} as const;
