project_id = "lyjfwnlindbsbbwjzefh"

[functions.daily-crypto-scanner]
verify_jwt = false

[functions.filter-crypto-universe]
verify_jwt = false

[functions.filter-equity-universe]
verify_jwt = false

[functions.daily-equity-scanner]
verify_jwt = false

[functions.etf-stream]
verify_jwt = false

[functions.fetch-etf-data]
verify_jwt = false

[functions.fetch-etf-metadata]
verify_jwt = false

[functions.test-canadian-apis]
verify_jwt = false

[functions.quotes]
verify_jwt = false

[functions.get-stored-prices]
verify_jwt = false

[functions.get-cached-drip]
verify_jwt = false

[functions.daily-drip-calculator]
verify_jwt = false

[functions.polygon-quotes]
verify_jwt = false

[functions.dividend-updater]
verify_jwt = false

[functions.yfinance-yields]
verify_jwt = false

[functions.finnhub-yields]
verify_jwt = false

[functions.tiingo-yields]
verify_jwt = false

[functions.yahoo-finance-test]
verify_jwt = false

[functions.update-canadian-prices]
verify_jwt = false

[functions.calculate-drip]
verify_jwt = false

[functions.get-single-price]
verify_jwt = false

[functions.bulk-price-update]
verify_jwt = false

[functions.fetch-historical-prices]
verify_jwt = false

[functions.update-historical-prices-daily]
verify_jwt = false

[functions.import-historical-prices]
verify_jwt = false

[functions.yfinance-rsi]
verify_jwt = false

[functions.alerts_ingest]
verify_jwt = false
