project_id = "lyjfwnlindbsbbwjzefh"

[functions.etf-stream]
verify_jwt = false

[functions.fetch-etf-data]
verify_jwt = false

[functions.test-canadian-apis]
verify_jwt = false

[functions.quotes]
verify_jwt = false

[functions.polygon-quotes]
verify_jwt = false

[functions.dividend-updater]
verify_jwt = false

[functions.yfinance-yields]
verify_jwt = false
