# 1) Replace the bad file with valid TOML
cat > netlify.toml <<'TOML'
[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# (Optional hardening headers)
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
TOML

# 2) If you previously also committed a bogus `_redirects` with shell lines, fix it too.
#    Otherwise, keep your existing SPA rule `/* /index.html 200`.
#    Here's a correct SPA redirects file (only if you need to recreate it):
cat > _redirects <<'TXT'
/*  /index.html  200
TXT

# 3) Commit and push
git add netlify.toml _redirects
git commit -m "Fix netlify.toml (valid TOML) and SPA redirects"
git push
