[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Use this if it's a single-page app (Vite/React) to route all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
