# nixpacks.toml (root of repo)
providers = ["node"]

[variables]
PORT = "3000"
NODE_VERSION = "20"    # or "22" if your app supports it

[phases.setup]
# Keep ONLY one node; no overlays, no corepack (not needed if you use npm)
nixPkgs = ["nodejs_20", "nodePackages.npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx next start -p ${PORT}"
