providers = ["node"]

[variables]
PORT = "3000"
NODE_VERSION = "20"   # <-- key line; 22 also fine if your app supports it

[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.npm", "corepack"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx next start -p ${PORT}"
