# nixpacks.toml (root of repo)
providers = ["node"]

[variables]
PORT = "3000"
NODE_VERSION = "20"    # or "22" if your app supports it

[phases.setup]
nixPkgs = ["nodejs_20"]
# Drop the overlay too—it's only needed when you install npm via Nix
# nixOverlays = []

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx next start -p ${PORT}"
