-- Insert new Purpose ETFs from Canada
INSERT INTO etfs (ticker, name, exchange, country, manager, provider_group, currency, underlying, fund, strategy, industry, distribution_frequency, active) VALUES 
('APLY.NE', 'Apple (AAPL) Yield Shares Purpose ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Apple (AAPL)', 'Apple (AAPL) Yield Shares Purpose ETF', 'Single-stock options income', 'Technology', 'Irregular', true),
('ATDY.NE', 'Purpose Couche-Tard (ATD) Yield Shares ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Alimentation Couche-Tard Inc. (ATD.TO)', 'Purpose Couche-Tard (ATD) Yield Shares ETF', 'Unknown', 'Unknown', 'Irregular', true),
('BNSY.NE', 'Purpose Scotiabank (BNS) Yield Shares ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'The Bank of Nova Scotia (BNS.TO)', 'Purpose Scotiabank (BNS) Yield Shares ETF', 'Unknown', 'Unknown', 'Monthly', true),
('BNY.NE', 'Purpose Brookfield (BN) Yield Shares ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Brookfield Corporation (BN.TO)', 'Purpose Brookfield (BN) Yield Shares ETF', 'Unknown', 'Unknown', 'Monthly', true),
('BRKY.NE', 'Berkshire Hathaway (BRK) Yield Shares Purpose ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Berkshire Hathaway (BRK.A)', 'Berkshire Hathaway (BRK) Yield Shares Purpose ETF', 'Unknown', 'Unknown', 'Irregular', true),
('BTCY.NE', 'Purpose Bitcoin Yield ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Bitcoin (BTC)', 'Purpose Bitcoin Yield ETF', 'Unknown', 'Unknown', 'Monthly', true),
('CNQY.NE', 'Purpose Canadian Natural Resources (CNQ) Yield Shares ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Canadian Natural Resources Ltd. (CNQ.TO)', 'Purpose Canadian Natural Resources (CNQ) Yield Shares ETF', 'Unknown', 'Unknown', 'Monthly', true),
('DOLY.NE', 'Purpose Dollarama (DOL) Yield Shares ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Dollarama Inc. (DOL.TO)', 'Purpose Dollarama (DOL) Yield Shares ETF', 'Unknown', 'Unknown', 'Monthly', true),
('ENBY.NE', 'Purpose Enbridge (ENB) Yield Shares ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Enbridge Inc. (ENB.TO)', 'Purpose Enbridge (ENB) Yield Shares ETF', 'Unknown', 'Unknown', 'Monthly', true),
('ETHY.NE', 'Purpose Ether Yield ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Ethereum (ETH)', 'Purpose Ether Yield ETF', 'Unknown', 'Unknown', 'Monthly', true),
('MSFY.NE', 'Microsoft (MSFT) Yield Shares Purpose ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Microsoft (MSFT)', 'Microsoft (MSFT) Yield Shares Purpose ETF', 'Unknown', 'Unknown', 'Monthly', true),
('RBCY.NE', 'Purpose RBC (RY) Yield Shares ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Royal Bank of Canada (RY.TO)', 'Purpose RBC (RY) Yield Shares ETF', 'Unknown', 'Unknown', 'Monthly', true),
('SHPY.NE', 'Purpose Shopify (SHOP) Yield Shares ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Shopify Inc. (SHOP.TO)', 'Purpose Shopify (SHOP) Yield Shares ETF', 'Unknown', 'Unknown', 'Monthly', true),
('TDY.NE', 'Purpose TD (TD) Yield Shares ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Toronto-Dominion Bank (TD.TO)', 'Purpose TD (TD) Yield Shares ETF', 'Unknown', 'Unknown', 'Monthly', true),
('TY.NE', 'Purpose TELUS (T) Yield Shares ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'TELUS Corporation (T.TO)', 'Purpose TELUS (T) Yield Shares ETF', 'Unknown', 'Unknown', 'Monthly', true),
('YAMD.NE', 'AMD (AMD) Yield Shares Purpose ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'AMD (AMD)', 'AMD (AMD) Yield Shares Purpose ETF', 'Unknown', 'Unknown', 'Monthly', true),
('YAMZ.NE', 'Amazon (AMZN) Yield Shares Purpose ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Amazon (AMZN)', 'Amazon (AMZN) Yield Shares Purpose ETF', 'Unknown', 'Unknown', 'Irregular', true),
('YAVG.NE', 'Broadcom (AVGO) Yield Shares Purpose ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Broadcom (AVGO)', 'Broadcom (AVGO) Yield Shares Purpose ETF', 'Unknown', 'Unknown', 'Monthly', true),
('YCON.NE', 'Coinbase (COIN) Yield Shares Purpose ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Coinbase (COIN)', 'Coinbase (COIN) Yield Shares Purpose ETF', 'Unknown', 'Unknown', 'Monthly', true),
('YCST.NE', 'Costco (COST) Yield Shares Purpose ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Costco (COST)', 'Costco (COST) Yield Shares Purpose ETF', 'Unknown', 'Unknown', 'Monthly', true),
('YGOG.NE', 'Alphabet (GOOGL) Yield Shares Purpose ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Alphabet (GOOG)', 'Alphabet (GOOGL) Yield Shares Purpose ETF', 'Unknown', 'Unknown', 'Monthly', true),
('YMAG.NE', 'Tech Innovators Yield Shares Purpose ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'BATMMAAN stocks (Basket Broadcom (AVGO), Apple (AAPL), Tesla (TSLA), Microsoft (MSFT), Meta (META), Amazon (AMZN), Alphabet (GOOGL/GOOG), Nvidia (NVDA))', 'Tech Innovators Yield Shares Purpose ETF', 'Single-stock options income', 'Unknown', 'Monthly', true),
('YMET.NE', 'Meta (META) Yield Shares Purpose ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Meta (META)', 'Meta (META) Yield Shares Purpose ETF', 'Unknown', 'Unknown', 'Monthly', true),
('YNET.NE', 'Netflix (NFLX) Yield Shares Purpose ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Netflix (NFLX)', 'Netflix (NFLX) Yield Shares Purpose ETF', 'Unknown', 'Unknown', 'Monthly', true),
('YNVD.NE', 'NVIDIA (NVDA) Yield Shares Purpose ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'NVIDIA (NVDA)', 'NVIDIA (NVDA) Yield Shares Purpose ETF', 'Unknown', 'Unknown', 'Irregular', true),
('YPLT.NE', 'Palantir (PLTR) Yield Shares Purpose ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Palantir (PLTR)', 'Palantir (PLTR) Yield Shares Purpose ETF', 'Unknown', 'Unknown', 'Monthly', true),
('YTSL.NE', 'Tesla (TSLA) Yield Shares Purpose ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'Tesla (TSLA)', 'Tesla (TSLA) Yield Shares Purpose ETF', 'Unknown', 'Unknown', 'Irregular', true),
('YUNH.NE', 'UnitedHealth Group (UNH) Yield Shares Purpose ETF', 'Cboe Canada', 'CA', 'Purpose', 'Purpose', 'CAD', 'UnitedHealth Group (UNH)', 'UnitedHealth Group (UNH) Yield Shares Purpose ETF', 'Unknown', 'Unknown', 'Monthly', true)
ON CONFLICT (ticker) DO UPDATE SET
  name = EXCLUDED.name,
  exchange = EXCLUDED.exchange,
  country = EXCLUDED.country,
  manager = EXCLUDED.manager,
  provider_group = EXCLUDED.provider_group,
  currency = EXCLUDED.currency,
  underlying = EXCLUDED.underlying,
  fund = EXCLUDED.fund,
  strategy = EXCLUDED.strategy,
  industry = EXCLUDED.industry,
  distribution_frequency = EXCLUDED.distribution_frequency,
  active = EXCLUDED.active,
  updated_at = now();